version: '3'
services:
  db:
    image: mariadb:10.2
    container_name: "${PROJECT_NAME}_db"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
      - $PWD/:/backups
    restart: always
  server:
    container_name: "${PROJECT_NAME}_app"
    depends_on:
      - db
    build: .
    image: georgetour-linux
    volumes:
      - ./app:/app
    restart: always
    labels:
      - 'traefik.backend=drupal'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    depends_on:
      - db
    links:
      - db:db
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      PMA_HOST: db
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.${PROJECT_BASE_URL}'
  traefik:
    image: traefik
    container_name: "${PROJECT_NAME}_traefik"
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '${PROJECT_PORT}:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  db_data:
    